* Planning Problems Examples

  This repository holds a few planning problems examples and its
  solutions using OptaPlanner and other suggested methods in the
  literature.

  Solutions other than OptaPlanner use python and a few dependencies
  listed below.

** Python dependencies

*** Ubuntu 13.10

    The linear programming problems are declared and solved using the
    [[http://tfinley.net/software/pyglpk/discussion.html][PyGLPK library]], the ubuntu package boundled in 13.10 is not recent
    enough, installation with [[http://www.pip-installer.org/en/latest/][pip]] inside a virtual environment is
    recommended but not mandatory. The required libraries for PyGLPK
    can be obtained from the ubuntu repositories with the commands:

    #+begin_src sh
    aptitude install glpk libgmp-dev
    #+end_src

    Then the PyGLPK package can be installed, optionally inside a
    virtualenv, with:

    #+begin_src sh
    pip install glpk
    #+end_src


*** Other Versions

    The python package is the same but the sources for the needed
    libraries are dependant on the system, no testing has been made on
    systems other than ubuntu, but it should work.
