* Ejemplos de Problemas de Planeación

  Este repositorio contiene algunos ejemplos de problemas de
  planeación junto con sus soluciones utilizando OptaPlanner y otras
  metodologías sugeridas en la literatura.

  Los problemas seleccionados tienen soluciones mediante métodos
  matemáticos diferentes a los utilizados por OptaPlanner y dichas
  soluciones se presentan como scripts en python con el fin de
  compararlas con OptaPlanner.

** Dependencias en Java

   Los principales requerimientos para ejecutar los proyectos maven
   son el Java SE Development Kit versión 7 o superior
   (preferiblemente de oracle), y maven versión 3.0.4 (en los
   repositorios estándard de ubuntu). Después de cumplir con estas
   dependencias, dentro de cada carpeta de proyectos maven (carpetas
   que contienen un archivo =pom.xml=), las pruebas pueden ser
   ejecutadas mediante:

   #+begin_src sh
   mvn test
   #+end_src

** Dependencias en Python

*** Ubuntu 13.10

    Los problemas de programación lineal son declarados y resueltos
    usando la [[http://tfinley.net/software/pyglpk/discussion.html][librería PyGLPK]], el paquete incluido en ubuntu 13.10 no
    es lo suficientemente reciente, por lo que se recomienda la
    instalación con [[http://www.pip-installer.org/en/latest/][pip]] dentro de un virtual environment aunque no es
    necesario. Las librerías necesarias para PyGLPK pueden ser
    obtenidas de los repositorios de ubuntu mediante los comandos:

    #+begin_src sh
    aptitude install glpk libgmp-dev
    #+end_src

    Luego los paquetes de PyGLPK pueden ser instalados, de manera
    opcional dentro de un [[http://virtualenvwrapper.readthedocs.org/en/latest/][virtualenv]], con:

    #+begin_src sh
    pip install glpk
    #+end_src

    Una vez instalados los paquetes anteriores, las soluciones en
    python se pueden ejecutar mediante:

    #+begin_src sh
    python $(nombre_archivo_a_ejecutar).py
    #+end_src


*** Otros Sistemas Operativos

    El paquete de python es el mismo pero las fuentes necesarias para
    las librerías dependen del sistema, no se han realizado pruebas en
    sistemas diferentes a Ubuntu, pero deberían funcionar.
